CREATE TABLE `directory_listings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`serviceKey` varchar(255) NOT NULL,
	`name` varchar(255) NOT NULL,
	`category` varchar(128) NOT NULL,
	`description` text,
	`area` varchar(128) NOT NULL DEFAULT 'Charlotte Metro',
	`phone` varchar(32),
	`website` text,
	`googlePlaceId` varchar(512),
	`googleRating` varchar(8),
	`reviewCount` int,
	`verifiedAddress` text,
	`hoursJson` text,
	`googleTypes` text,
	`priceLevel` int,
	`featured` boolean NOT NULL DEFAULT false,
	`active` boolean NOT NULL DEFAULT true,
	`addedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `directory_listings_id` PRIMARY KEY(`id`),
	CONSTRAINT `directory_listings_serviceKey_unique` UNIQUE(`serviceKey`)
);
