/* ============================================
   SETTLE CLT — Events Data
   Categories and seed events for the events system.
   ============================================ */

export type EventType = "recurring" | "one_time";
export type EventCost = "free" | "paid" | "mixed";

export interface EventCategory {
  id: string;
  name: string;
  icon: string;
}

export interface SeedEvent {
  name: string;
  slug: string;
  type: EventType;
  category: string;
  organizer?: string;
  organizerWebsite?: string;
  venue?: string;
  venueArea?: string;
  startDate?: string;
  endDate?: string;
  recurringPattern?: string;
  sourceUrl: string;
  sourceVerified?: boolean;
  newcomerFriendly?: boolean;
  featured?: boolean;
  description?: string;
  neighborhood?: string;
  cost?: EventCost;
  rsvpUrl?: string;
}

export const EVENT_CATEGORIES: EventCategory[] = [
  { id: "community", name: "Community & Markets", icon: "🏘️" },
  { id: "festivals", name: "Festivals & Major Events", icon: "🎪" },
  { id: "neighborhood", name: "Neighborhood Events", icon: "📍" },
  { id: "professional", name: "Professional & Networking", icon: "🤝" },
  { id: "family", name: "Family & Kids", icon: "👨‍👩‍👧" },
  { id: "sports", name: "Sports & Recreation", icon: "🏃" },
];

export const SEED_EVENTS: SeedEvent[] = [
  {
    name: "Charlotte SHOUT!",
    slug: "charlotte-shout",
    type: "one_time",
    category: "festivals",
    organizer: "Charlotte Center City Partners",
    organizerWebsite: "https://www.charlotteshout.com",
    venue: "Uptown Charlotte",
    venueArea: "Uptown",
    startDate: "2026-04-10",
    endDate: "2026-04-26",
    sourceUrl: "https://www.charlotteshout.com",
    featured: true,
    newcomerFriendly: true,
    description:
      "Charlotte's signature spring arts and culture festival spanning Uptown with live music, food, art installations, and performances.",
    neighborhood: "Uptown",
    cost: "mixed",
  },
  {
    name: "Taco Intercambio",
    slug: "taco-intercambio",
    type: "recurring",
    category: "community",
    organizer: "Latin American Coalition",
    organizerWebsite: "https://www.latinamericancoalition.org",
    venue: "Midwood International & Cultural Center",
    venueArea: "Central Charlotte",
    recurringPattern: "Monthly, first Friday",
    sourceUrl: "https://www.latinamericancoalition.org/events",
    newcomerFriendly: true,
    description:
      "A free monthly community gathering celebrating Latin American culture through tacos, music, and dancing.",
    neighborhood: "Plaza Midwood",
    cost: "free",
  },
  {
    name: "South End Wine Walk",
    slug: "south-end-wine-walk",
    type: "recurring",
    category: "community",
    organizer: "South End District",
    organizerWebsite: "https://southendclt.com",
    venue: "South End Rail Trail",
    venueArea: "South End",
    recurringPattern: "Seasonal, spring and fall",
    sourceUrl: "https://southendclt.com/events/south-end-wine-walk",
    featured: true,
    newcomerFriendly: true,
    description:
      "A walkable wine tasting event through South End's best restaurants and wine bars along the Rail Trail.",
    neighborhood: "South End",
    cost: "paid",
  },
  {
    name: "Charlotte Farmers Market",
    slug: "charlotte-farmers-market",
    type: "recurring",
    category: "community",
    organizer: "NC Department of Agriculture",
    organizerWebsite: "https://www.ncagr.gov",
    venue: "Charlotte Regional Farmers Market",
    venueArea: "West Charlotte",
    recurringPattern: "Year-round, Tue–Sun",
    sourceUrl: "https://www.ncagr.gov/markets/facilities/markets/charlotte",
    newcomerFriendly: true,
    description:
      "Year-round regional farmers market with local produce, meats, baked goods, and crafts.",
    neighborhood: "West Charlotte",
    cost: "free",
  },
  {
    name: "Optimist Hall Night Market",
    slug: "optimist-hall-night-market",
    type: "recurring",
    category: "community",
    organizer: "Optimist Hall",
    organizerWebsite: "https://optimisthall.com",
    venue: "Optimist Hall",
    venueArea: "NoDa",
    recurringPattern: "Monthly, second Saturday",
    sourceUrl: "https://optimisthall.com/events",
    featured: false,
    newcomerFriendly: true,
    description:
      "Evening market at Optimist Hall with local makers, live music, and food hall vendors.",
    neighborhood: "NoDa",
    cost: "free",
  },
  {
    name: "Cedar Street Night Market",
    slug: "cedar-street-night-market",
    type: "recurring",
    category: "neighborhood",
    organizer: "Camp North End",
    organizerWebsite: "https://campnorthend.com",
    venue: "Camp North End",
    venueArea: "North End",
    recurringPattern: "Monthly, summer",
    sourceUrl: "https://campnorthend.com/events",
    description:
      "Neighborhood night market at Camp North End featuring local artists, food trucks, and live music.",
    neighborhood: "Camp North End",
    cost: "free",
  },
  {
    name: "Charlotte Black Film Festival",
    slug: "charlotte-black-film-festival",
    type: "one_time",
    category: "festivals",
    organizer: "Charlotte Black Film Festival",
    organizerWebsite: "https://www.charlotteblackfilmfestival.com",
    venue: "Gantt Center",
    venueArea: "Uptown",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    sourceUrl: "https://www.charlotteblackfilmfestival.com",
    featured: true,
    newcomerFriendly: false,
    description:
      "Annual festival showcasing Black filmmakers with screenings, panels, and networking events at the Gantt Center.",
    neighborhood: "Uptown",
    cost: "paid",
  },
  {
    name: "Charlotte Tech Breakfast",
    slug: "charlotte-tech-breakfast",
    type: "recurring",
    category: "professional",
    organizer: "Charlotte Tech Breakfast",
    organizerWebsite: "https://www.meetup.com/charlotte-tech-breakfast",
    venue: "Packard Place",
    venueArea: "Uptown",
    recurringPattern: "Monthly, second Tuesday",
    sourceUrl: "https://www.meetup.com/charlotte-tech-breakfast",
    newcomerFriendly: true,
    description:
      "Monthly morning meetup for Charlotte's tech community — founders, developers, and professionals networking over coffee.",
    neighborhood: "Uptown",
    cost: "free",
  },
  {
    name: "Queen City Bike Party",
    slug: "queen-city-bike-party",
    type: "recurring",
    category: "sports",
    organizer: "Queen City Bike Party",
    organizerWebsite: "https://www.queencitybikeparty.org",
    venue: "Various start locations",
    venueArea: "Charlotte Metro",
    recurringPattern: "Monthly, last Friday",
    sourceUrl: "https://www.queencitybikeparty.org",
    newcomerFriendly: true,
    description:
      "A free, community bike ride through Charlotte neighborhoods with a different route each month. All speeds welcome.",
    neighborhood: "Charlotte Metro",
    cost: "free",
  },
  {
    name: "Discovery Place Kids Summer Camps",
    slug: "discovery-place-kids-summer-camps",
    type: "recurring",
    category: "family",
    organizer: "Discovery Place",
    organizerWebsite: "https://www.discoveryplace.org",
    venue: "Discovery Place Science",
    venueArea: "Uptown",
    startDate: "2026-06-15",
    endDate: "2026-08-15",
    recurringPattern: "Weekly, summer",
    sourceUrl: "https://www.discoveryplace.org/camps",
    featured: false,
    newcomerFriendly: true,
    description:
      "Hands-on STEM summer camps for kids at Discovery Place Science — robotics, coding, and science exploration.",
    neighborhood: "Uptown",
    cost: "paid",
  },
  {
    name: "Alive After Five",
    slug: "alive-after-five",
    type: "recurring",
    category: "neighborhood",
    organizer: "Epicenter",
    organizerWebsite: "https://theepicentre.com",
    venue: "Epicenter",
    venueArea: "Uptown",
    recurringPattern: "Weekly, Thursdays, Apr–Oct",
    sourceUrl: "https://theepicentre.com/events",
    featured: true,
    newcomerFriendly: true,
    description:
      "Charlotte's longest-running weekly free outdoor concert series in the Epicenter, featuring live bands every Thursday.",
    neighborhood: "Uptown",
    cost: "free",
  },
  {
    name: "Charlotte Pride Festival & Parade",
    slug: "charlotte-pride-festival-parade",
    type: "one_time",
    category: "festivals",
    organizer: "Charlotte Pride",
    organizerWebsite: "https://www.charlottepride.org",
    venue: "Uptown Charlotte",
    venueArea: "Uptown",
    startDate: "2026-08-15",
    endDate: "2026-08-16",
    sourceUrl: "https://www.charlottepride.org/festival",
    featured: true,
    newcomerFriendly: true,
    description:
      "The largest LGBTQ+ pride celebration in the Carolinas with a parade, festival, live entertainment, and community resources.",
    neighborhood: "Uptown",
    cost: "free",
  },
  {
    name: "Queen's Feast: Charlotte Restaurant Week",
    slug: "queens-feast-charlotte-restaurant-week",
    type: "one_time",
    category: "festivals",
    organizer: "Charlotte's Got A Lot",
    organizerWebsite: "https://www.charlottesgotalot.com",
    venue: "Various Charlotte restaurants",
    venueArea: "Charlotte Metro",
    startDate: "2026-01-23",
    endDate: "2026-02-01",
    recurringPattern: "Annual, winter",
    sourceUrl: "https://www.charlottesgotalot.com/events/eat-drink/queens-feast-winter-edition",
    sourceVerified: true,
    newcomerFriendly: true,
    featured: true,
    description: "Three-course prix-fixe menus from nearly 100 Charlotte region restaurants.",
    neighborhood: "Charlotte Metro",
    cost: "paid"
  },
  {
    name: "NASCAR Hall of Fame Induction Weekend",
    slug: "nascar-hall-of-fame-induction-weekend",
    type: "one_time",
    category: "festivals",
    organizer: "NASCAR Hall of Fame",
    organizerWebsite: "https://www.nascarhall.com",
    venue: "NASCAR Hall of Fame",
    venueArea: "Uptown",
    startDate: "2026-01-22",
    endDate: "2026-01-24",
    sourceUrl: "https://www.nascarhall.com/hall-of-famers/induction-weekend",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Racing legends enshrined during Induction Weekend at the NASCAR Hall of Fame in Uptown Charlotte.",
    neighborhood: "Uptown",
    cost: "paid"
  },
  {
    name: "Queen City Brewers Festival",
    slug: "queen-city-brewers-festival",
    type: "one_time",
    category: "festivals",
    organizer: "Queen City Brewers Festival",
    venue: "Charlotte Metro",
    venueArea: "Charlotte Metro",
    startDate: "2026-02-07",
    endDate: "2026-02-07",
    recurringPattern: "Annual, February",
    sourceUrl: "https://www.charlottesgotalot.com/events/eat-drink/queen-city-brewers-festival",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Sip more than 25 local and regional beers at this annual winter beer festival.",
    neighborhood: "Charlotte Metro",
    cost: "paid"
  },
  {
    name: "Savor Charlotte",
    slug: "savor-charlotte",
    type: "one_time",
    category: "festivals",
    organizer: "Charlotte's Got A Lot",
    organizerWebsite: "https://www.charlottesgotalot.com",
    venue: "Various Charlotte restaurants",
    venueArea: "Charlotte Metro",
    startDate: "2026-03-11",
    endDate: "2026-03-28",
    recurringPattern: "Annual, March",
    sourceUrl: "https://www.charlottesgotalot.com/savor",
    sourceVerified: true,
    newcomerFriendly: true,
    featured: true,
    description: "Interactive classes, demonstrations, special menus and exclusive offers from Charlotte tastemakers.",
    neighborhood: "Charlotte Metro",
    cost: "paid"
  },
  {
    name: "Tuck Fest",
    slug: "tuck-fest",
    type: "one_time",
    category: "sports",
    organizer: "U.S. National Whitewater Center",
    organizerWebsite: "https://tuckfest.whitewater.org",
    venue: "U.S. National Whitewater Center",
    venueArea: "West Charlotte",
    startDate: "2026-04-03",
    endDate: "2026-04-05",
    recurringPattern: "Annual, April",
    sourceUrl: "https://tuckfest.whitewater.org",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Three-day festival with trail running, kayaking, biking, climbing, obstacle racing, and live music at the Whitewater Center.",
    neighborhood: "West Charlotte",
    cost: "paid"
  },
  {
    name: "Truist Championship",
    slug: "truist-championship",
    type: "one_time",
    category: "sports",
    organizer: "PGA Tour",
    organizerWebsite: "https://www.truistchampionship.com",
    venue: "Quail Hollow Club",
    venueArea: "South Charlotte",
    startDate: "2026-05-06",
    endDate: "2026-05-10",
    recurringPattern: "Annual, May",
    sourceUrl: "https://www.truistchampionship.com",
    sourceVerified: true,
    newcomerFriendly: false,
    description: "PGA Tour signature event featuring top golfers at Quail Hollow Club.",
    neighborhood: "South Charlotte",
    cost: "paid"
  },
  {
    name: "Coca-Cola 600",
    slug: "coca-cola-600",
    type: "one_time",
    category: "sports",
    organizer: "Charlotte Motor Speedway",
    organizerWebsite: "https://www.charlottemotorspeedway.com",
    venue: "Charlotte Motor Speedway",
    venueArea: "Concord",
    startDate: "2026-05-24",
    endDate: "2026-05-24",
    recurringPattern: "Annual, May",
    sourceUrl: "https://www.charlottemotorspeedway.com/events/coca-cola-600/",
    sourceVerified: true,
    newcomerFriendly: true,
    featured: true,
    description: "NASCAR Cup Series race at Charlotte Motor Speedway on Memorial Day weekend.",
    neighborhood: "Concord",
    cost: "paid"
  },
  {
    name: "Taste of Charlotte",
    slug: "taste-of-charlotte",
    type: "one_time",
    category: "festivals",
    organizer: "Taste of Charlotte",
    venue: "Uptown Charlotte",
    venueArea: "Uptown",
    startDate: "2026-06-05",
    endDate: "2026-06-07",
    recurringPattern: "Annual, June",
    sourceUrl: "https://www.tasteofcharlotte.com",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Food festival in Uptown featuring tastings from local restaurants and live entertainment.",
    neighborhood: "Uptown",
    cost: "free"
  },
  {
    name: "Around the Crown 10K",
    slug: "around-the-crown-10k",
    type: "one_time",
    category: "sports",
    organizer: "Around the Crown 10K",
    organizerWebsite: "https://aroundthecrown10k.com",
    venue: "I-277 loop",
    venueArea: "Uptown",
    startDate: "2026-09-06",
    endDate: "2026-09-06",
    recurringPattern: "Annual, September",
    sourceUrl: "https://aroundthecrown10k.com",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Race along I-277 in Uptown Charlotte, one of the city's most popular 10K events.",
    neighborhood: "Uptown",
    cost: "paid"
  },
  {
    name: "Charlotte Film Festival",
    slug: "charlotte-film-festival-sept",
    type: "one_time",
    category: "festivals",
    organizer: "Charlotte Film Festival",
    organizerWebsite: "https://www.charlottefilm.com",
    venue: "Independent Picture House",
    venueArea: "NoDa",
    startDate: "2026-09-22",
    endDate: "2026-09-27",
    recurringPattern: "Annual, September",
    sourceUrl: "https://www.charlottefilm.com/events/film/charlotte-film-festival",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Independent films from all genres screened at Independent Picture House in NoDa.",
    neighborhood: "NoDa",
    cost: "paid"
  },
  {
    name: "Novant Health Thanksgiving Eve Parade",
    slug: "novant-health-thanksgiving-eve-parade",
    type: "one_time",
    category: "festivals",
    organizer: "Charlotte Center City Partners",
    organizerWebsite: "https://www.charlottecentercity.org",
    venue: "Uptown Charlotte",
    venueArea: "Uptown",
    startDate: "2026-11-25",
    endDate: "2026-11-25",
    recurringPattern: "Annual, Thanksgiving Eve",
    sourceUrl: "https://novanthealththanksgivingparade.com",
    sourceVerified: true,
    newcomerFriendly: true,
    featured: true,
    description: "77-year tradition kicking off the holiday season with floats, balloons, and performances in Uptown.",
    neighborhood: "Uptown",
    cost: "free"
  },
  {
    name: "CLT NYE",
    slug: "clt-nye",
    type: "one_time",
    category: "festivals",
    organizer: "Charlotte Center City Partners",
    organizerWebsite: "https://www.charlottecentercity.org",
    venue: "Uptown Charlotte",
    venueArea: "Uptown",
    startDate: "2026-12-31",
    endDate: "2026-12-31",
    recurringPattern: "Annual, New Year's Eve",
    sourceUrl: "https://uptowncharlotte.com/events/signature-events/cltnye",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Charlotte's official New Year's party with live music, fireworks, and the lighting of the Queen City crown.",
    neighborhood: "Uptown",
    cost: "free"
  },
  {
    name: "South End Farmers Market at Atherton Mill",
    slug: "south-end-farmers-market-atherton",
    type: "recurring",
    category: "community",
    organizer: "South End District",
    organizerWebsite: "https://southendclt.org",
    venue: "Atherton Mill",
    venueArea: "South End",
    recurringPattern: "Every Sunday",
    sourceUrl: "https://southendclt.org/events/south-end-market",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Weekly farmers market at Atherton Mill with local artisans, farmers, and food vendors.",
    neighborhood: "South End",
    cost: "free"
  },
  {
    name: "First Friday Gallery Crawl",
    slug: "first-friday-gallery-crawl",
    type: "recurring",
    category: "neighborhood",
    organizer: "South End District",
    organizerWebsite: "https://southendclt.org",
    venue: "Various South End galleries",
    venueArea: "South End",
    recurringPattern: "First Friday of every month",
    sourceUrl: "https://southendclt.org/events/first-friday",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Monthly gallery crawl with special receptions, live painting, music, and more in South End.",
    neighborhood: "South End",
    cost: "free"
  },
  {
    name: "Camden Commons",
    slug: "camden-commons",
    type: "recurring",
    category: "neighborhood",
    organizer: "South End District",
    organizerWebsite: "https://southendclt.org",
    venue: "Camden Road",
    venueArea: "South End",
    startDate: "2026-03-22",
    recurringPattern: "Seasonal, summer select dates",
    sourceUrl: "https://southendclt.org/events/camden-commons",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Outdoor living room on Camden Road where you can eat, play games, and hang out in South End.",
    neighborhood: "South End",
    cost: "free"
  },
  {
    name: "Movies in the Park South End",
    slug: "movies-in-the-park-south-end",
    type: "recurring",
    category: "neighborhood",
    organizer: "South End District",
    organizerWebsite: "https://southendclt.org",
    venue: "Various South End parks",
    venueArea: "South End",
    recurringPattern: "Seasonal, fall",
    sourceUrl: "https://southendclt.org/events/movies-in-the-park",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Outdoor movie screenings in South End parks during the fall season.",
    neighborhood: "South End",
    cost: "free"
  },
  {
    name: "Rail Trail Lights",
    slug: "rail-trail-lights",
    type: "one_time",
    category: "festivals",
    organizer: "South End District",
    organizerWebsite: "https://southendclt.org",
    venue: "Charlotte Rail Trail",
    venueArea: "South End",
    recurringPattern: "Annual, spring",
    sourceUrl: "https://southendclt.org/events/i-heart-rail-trail-lights",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Interactive light art installations along the Charlotte Rail Trail each spring.",
    neighborhood: "South End",
    cost: "free"
  },
  {
    name: "NoDa Bizarre",
    slug: "noda-bizarre",
    type: "one_time",
    category: "neighborhood",
    organizer: "NoDa NBA",
    organizerWebsite: "https://www.noda.org",
    venue: "Johnston YMCA",
    venueArea: "NoDa",
    startDate: "2026-08-01",
    recurringPattern: "Annual",
    sourceUrl: "https://www.noda.org/noda-bizarre",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Vibrant celebration of art, creativity, and community in NoDa with vendors, performances, and art markets.",
    neighborhood: "NoDa",
    cost: "free"
  },
  {
    name: "NoDa Neighborhood Hangs",
    slug: "noda-neighborhood-hangs",
    type: "recurring",
    category: "neighborhood",
    organizer: "NoDa NBA",
    organizerWebsite: "https://www.noda.org",
    venue: "Various NoDa venues",
    venueArea: "NoDa",
    recurringPattern: "Monthly",
    sourceUrl: "https://www.noda.org/noda-events",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Monthly community hangout events at various NoDa venues.",
    neighborhood: "NoDa",
    cost: "free"
  },
  {
    name: "Live Friday Nights at Camp",
    slug: "live-friday-nights-at-camp",
    type: "recurring",
    category: "neighborhood",
    organizer: "Camp North End",
    organizerWebsite: "https://camp.nc",
    venue: "Camp North End",
    venueArea: "North End",
    recurringPattern: "Weekly, Fridays",
    sourceUrl: "https://camp.nc/friday-night-music/",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Free live music every Friday night at Camp North End's Boileryard.",
    neighborhood: "Camp North End",
    cost: "free"
  },
  {
    name: "Crossroad Cinema",
    slug: "crossroad-cinema",
    type: "recurring",
    category: "neighborhood",
    organizer: "Camp North End",
    organizerWebsite: "https://camp.nc",
    venue: "Camp North End",
    venueArea: "North End",
    recurringPattern: "Weekly, summer",
    sourceUrl: "https://camp.nc/movies/",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Outdoor movie screenings at Camp North End during summer evenings.",
    neighborhood: "Camp North End",
    cost: "free"
  },
  {
    name: "Mistletoe Market",
    slug: "mistletoe-market",
    type: "one_time",
    category: "community",
    organizer: "Camp North End",
    organizerWebsite: "https://camp.nc",
    venue: "Camp North End",
    venueArea: "North End",
    startDate: "2026-11-01",
    endDate: "2026-12-23",
    recurringPattern: "Annual, winter",
    sourceUrl: "https://camp.nc/mistletoe-market/",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Holiday market at Camp North End with local vendors, gifts, and seasonal festivities.",
    neighborhood: "Camp North End",
    cost: "free"
  },
  {
    name: "Ice Skating at Camp",
    slug: "ice-skating-at-camp",
    type: "recurring",
    category: "family",
    organizer: "Camp North End",
    organizerWebsite: "https://camp.nc",
    venue: "Camp North End",
    venueArea: "North End",
    startDate: "2026-11-01",
    endDate: "2027-01-31",
    recurringPattern: "Seasonal, winter",
    sourceUrl: "https://camp.nc/iceskating/",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Outdoor ice skating rink at Camp North End during winter months.",
    neighborhood: "Camp North End",
    cost: "paid"
  },
  {
    name: "Charlotte Vintage Market at Optimist Hall",
    slug: "charlotte-vintage-market-optimist",
    type: "recurring",
    category: "community",
    organizer: "Charlotte Vintage Market",
    venue: "Optimist Hall",
    venueArea: "NoDa",
    recurringPattern: "Monthly, select Saturdays",
    sourceUrl: "https://www.optimisthall.com/events",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Over 40 local vendors selling vintage clothing, jewelry, and goods at Optimist Hall's East Lawn.",
    neighborhood: "NoDa",
    cost: "free"
  },
  {
    name: "Charlotte Symphony: Back to the Future in Concert",
    slug: "charlotte-symphony-back-to-the-future",
    type: "one_time",
    category: "festivals",
    organizer: "Blumenthal Arts",
    organizerWebsite: "https://www.blumenthalarts.org",
    venue: "Belk Theater",
    venueArea: "Uptown",
    startDate: "2026-10-02",
    endDate: "2026-10-03",
    sourceUrl: "https://www.blumenthalarts.org/EVENTS",
    sourceVerified: true,
    newcomerFriendly: false,
    description: "Charlotte Symphony performs the Back to the Future score live with the film at Belk Theater.",
    neighborhood: "Uptown",
    cost: "paid"
  },
  {
    name: "The Cher Show",
    slug: "the-cher-show",
    type: "one_time",
    category: "festivals",
    organizer: "Blumenthal Arts",
    organizerWebsite: "https://www.blumenthalarts.org",
    venue: "Belk Theater",
    venueArea: "Uptown",
    startDate: "2026-08-28",
    endDate: "2026-08-29",
    sourceUrl: "https://www.blumenthalarts.org/events",
    sourceVerified: true,
    newcomerFriendly: false,
    description: "Broadway hit musical about Cher's life and career at Belk Theater.",
    neighborhood: "Uptown",
    cost: "paid"
  },
  {
    name: "Science on the Rocks",
    slug: "science-on-the-rocks",
    type: "recurring",
    category: "professional",
    organizer: "Discovery Place",
    organizerWebsite: "https://discoveryplace.org",
    venue: "Discovery Place Science",
    venueArea: "Uptown",
    recurringPattern: "Monthly, select evenings",
    sourceUrl: "https://discoveryplace.org/adult-events/science-on-the-rocks",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "21+ after-hours events with hands-on workshops, private gatherings, and science fun at Discovery Place.",
    neighborhood: "Uptown",
    cost: "paid"
  },
  {
    name: "Matthews Summerfest",
    slug: "matthews-summerfest",
    type: "one_time",
    category: "festivals",
    organizer: "Town of Matthews",
    organizerWebsite: "https://www.matthewsnc.gov",
    venue: "Stumptown Park",
    venueArea: "Matthews",
    startDate: "2026-05-08",
    endDate: "2026-05-09",
    recurringPattern: "Annual, May",
    sourceUrl: "https://www.matthewsnc.gov/pview.aspx?id=20793",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Two-day music and food festival in Matthews with live bands, food vendors, and family activities.",
    neighborhood: "Matthews",
    cost: "free"
  },
  {
    name: "Matthews Farmers Market",
    slug: "matthews-farmers-market",
    type: "recurring",
    category: "community",
    organizer: "Town of Matthews",
    organizerWebsite: "https://www.matthewsnc.gov",
    venue: "Downtown Matthews",
    venueArea: "Matthews",
    recurringPattern: "Saturday mornings, May-October",
    sourceUrl: "https://www.matthewsnc.gov/specialevents",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Weekly farmers market in downtown Matthews with local produce, baked goods, and crafts.",
    neighborhood: "Matthews",
    cost: "free"
  },
  {
    name: "Lake Norman Performing Arts Shows",
    slug: "lake-norman-performing-arts-shows",
    type: "recurring",
    category: "festivals",
    organizer: "Visit Lake Norman",
    organizerWebsite: "https://www.visitlakenorman.org",
    venue: "Various Lake Norman venues",
    venueArea: "Lake Norman",
    recurringPattern: "Seasonal",
    sourceUrl: "https://www.visitlakenorman.org/events/",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Performing arts shows and concerts throughout the Lake Norman area.",
    neighborhood: "Lake Norman",
    cost: "mixed"
  },
  {
    name: "North Meck Community Farmers Market",
    slug: "north-meck-community-farmers-market",
    type: "recurring",
    category: "community",
    organizer: "Charlotte Food Policy Council",
    organizerWebsite: "https://www.charlottefoodpolicy.com/nmcfm",
    venue: "Cornelius Town Hall",
    venueArea: "Cornelius",
    recurringPattern: "Saturday mornings, year-round",
    sourceUrl: "https://www.cornelius.org/calendar.php",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Year-round community farmers market at Cornelius Town Hall with local produce, crafts, and food vendors.",
    neighborhood: "Cornelius",
    cost: "free"
  },
  {
    name: "U.S. National Whitewater Center Events",
    slug: "us-national-whitewater-center-events",
    type: "recurring",
    category: "sports",
    organizer: "U.S. National Whitewater Center",
    organizerWebsite: "https://www.usnwc.org",
    venue: "U.S. National Whitewater Center",
    venueArea: "West Charlotte",
    recurringPattern: "Year-round",
    sourceUrl: "https://www.usnwc.org/events/",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Year-round outdoor events including trail running, kayaking, biking, concerts, and festivals at the Whitewater Center.",
    neighborhood: "West Charlotte",
    cost: "paid"
  },
  {
    name: "Shop Small Saturday South End",
    slug: "shop-small-saturday-south-end",
    type: "one_time",
    category: "community",
    organizer: "South End District",
    organizerWebsite: "https://southendclt.org",
    venue: "South End",
    venueArea: "South End",
    startDate: "2026-11-28",
    recurringPattern: "Annual, winter holiday season",
    sourceUrl: "https://southendclt.org/events/shop-small-saturday",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Celebrate South End's unique local retail with pop-up markets, one-of-a-kind shops, and holiday cheer.",
    neighborhood: "South End",
    cost: "free"
  },
  {
    name: "Victoria Yards",
    slug: "victoria-yards",
    type: "recurring",
    category: "neighborhood",
    organizer: "Charlotte Center City Partners",
    organizerWebsite: "https://www.charlottecentercity.org",
    venue: "Uptown Charlotte",
    venueArea: "Uptown",
    recurringPattern: "Ongoing programming",
    sourceUrl: "https://uptowncharlotte.com/events/victoria-yards",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Ongoing programming featuring craft brews, live music, murals, and surprises for all ages in Uptown.",
    neighborhood: "Uptown",
    cost: "free"
  },
  {
    name: "Winter at the Whitewater Center",
    slug: "winter-at-the-whitewater-center",
    type: "recurring",
    category: "sports",
    organizer: "U.S. National Whitewater Center",
    organizerWebsite: "https://www.usnwc.org",
    venue: "U.S. National Whitewater Center",
    venueArea: "West Charlotte",
    recurringPattern: "Seasonal, December-February",
    sourceUrl: "https://www.charlottesgotalot.com/blog/adventure/experience-winter-at-the-whitewater-center",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Winter outdoor activities including ice skating, trail running, and bonfires at the Whitewater Center.",
    neighborhood: "West Charlotte",
    cost: "paid"
  },
  {
    name: "Titanic: The Exhibition",
    slug: "titanic-the-exhibition",
    type: "one_time",
    category: "festivals",
    organizer: "Charlotte's Got A Lot",
    organizerWebsite: "https://www.charlottesgotalot.com",
    venue: "The Park Expo and Conference Center",
    venueArea: "Charlotte Metro",
    startDate: "2026-05-15",
    endDate: "2026-09-07",
    sourceUrl: "https://www.charlottesgotalot.com/events",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Immersive exhibition exploring the Titanic's story with artifacts and interactive displays.",
    neighborhood: "Charlotte Metro",
    cost: "paid"
  },
  {
    name: "Center City Vision Awards",
    slug: "center-city-vision-awards",
    type: "one_time",
    category: "professional",
    organizer: "Charlotte Center City Partners",
    organizerWebsite: "https://www.charlottecentercity.org",
    venue: "Uptown Charlotte",
    venueArea: "Uptown",
    recurringPattern: "Annual",
    sourceUrl: "https://www.charlottecentercity.org/initiatives/center-city-vision-awards",
    sourceVerified: true,
    newcomerFriendly: false,
    description: "Annual awards recognizing contributions making Center City more vibrant and extraordinary.",
    neighborhood: "Uptown",
    cost: "paid"
  },
  {
    name: "Charlotte Crown Home Opener",
    slug: "charlotte-crown-home-opener",
    type: "one_time",
    category: "sports",
    organizer: "Charlotte Crown",
    venue: "Bojangles Coliseum",
    venueArea: "Charlotte Metro",
    startDate: "2026-05-21",
    endDate: "2026-05-21",
    sourceUrl: "https://crownupshot.com/",
    sourceVerified: true,
    newcomerFriendly: true,
    description: "Inaugural home opener for Charlotte Crown, the new professional women's basketball team, at Bojangles Coliseum.",
    neighborhood: "Charlotte Metro",
    cost: "paid"
  },
  {
    name: "MLS All-Star Week",
    slug: "mls-all-star-week",
    type: "one_time",
    category: "sports",
    organizer: "MLS",
    venue: "Bank of America Stadium",
    venueArea: "Uptown",
    startDate: "2026-07-20",
    endDate: "2026-07-26",
    sourceUrl: "https://www.mlssoccer.com/news/charlotte-to-host-2026-mls-all-star-game",
    sourceVerified: true,
    newcomerFriendly: true,
    featured: true,
    description: "Week-long celebration of soccer including MLS All-Star Skills Challenge and MLS NEXT All-Star Game at Bank of America Stadium.",
    neighborhood: "Uptown",
    cost: "paid"
  },
];
