import mysql from "mysql2/promise";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("DATABASE_URL not set");
  process.exit(1);
}

const events = [
  // THIS WEEK (March 23-29, 2026)
  { title: "South End Wine Walk", slug: "south-end-wine-walk-mar-2026", description: "Explore South End's best restaurants and bars with wine tastings, small bites, and live music along the Rail Trail.", startDate: "2026-03-26 18:00:00", endDate: "2026-03-26 21:00:00", venueName: "South End Rail Trail", venueAddress: "South End, Charlotte, NC", neighborhood: "South End", category: "food-drink", isFeatured: "yes", status: "published" },
  { title: "NoDa Gallery Crawl", slug: "noda-gallery-crawl-mar-2026", description: "Monthly gallery crawl through NoDa's vibrant arts district. Free admission to all participating galleries, studios, and pop-up exhibitions.", startDate: "2026-03-27 18:00:00", endDate: "2026-03-27 22:00:00", venueName: "NoDa Arts District", venueAddress: "North Davidson St, Charlotte, NC", neighborhood: "NoDa", category: "arts-culture", isFeatured: "yes", status: "published" },
  { title: "Charlotte Knights vs Durham Bulls", slug: "knights-vs-durham-mar-2026", description: "Opening week baseball at Truist Field! Come watch the Charlotte Knights take on the Durham Bulls with fireworks after the game.", startDate: "2026-03-27 19:05:00", endDate: "2026-03-27 22:00:00", venueName: "Truist Field", venueAddress: "324 S Mint St, Charlotte, NC 28202", neighborhood: "Uptown", category: "sports", isFeatured: "yes", status: "published" },
  { title: "Uptown Farmers Market", slug: "uptown-farmers-market-mar-28", description: "Weekly farmers market featuring local produce, artisan goods, fresh baked bread, and handmade crafts from Charlotte-area farms.", startDate: "2026-03-28 09:00:00", endDate: "2026-03-28 13:00:00", venueName: "7th Street Public Market", venueAddress: "224 E 7th St, Charlotte, NC 28202", neighborhood: "Uptown", category: "markets", isFeatured: "no", status: "published" },
  { title: "Free Yoga in Romare Bearden Park", slug: "free-yoga-romare-bearden-mar-28", description: "Start your Saturday morning with free outdoor yoga overlooking the Charlotte skyline. All levels welcome, bring your own mat.", startDate: "2026-03-28 09:00:00", endDate: "2026-03-28 10:00:00", venueName: "Romare Bearden Park", venueAddress: "300 S Church St, Charlotte, NC 28202", neighborhood: "Uptown", category: "free", isFeatured: "no", status: "published" },
  { title: "Plaza Midwood Pub Run", slug: "plaza-midwood-pub-run-mar-28", description: "A 3-mile fun run through Plaza Midwood with stops at local breweries and bars. Registration includes a free drink at each stop.", startDate: "2026-03-28 14:00:00", endDate: "2026-03-28 18:00:00", venueName: "Thomas Street Tavern", venueAddress: "1218 Thomas Ave, Charlotte, NC 28205", neighborhood: "Plaza Midwood", category: "community", isFeatured: "no", status: "published" },

  // NEXT WEEK (March 30 - April 5)
  { title: "Miguel: CAOS Tour", slug: "miguel-caos-tour-charlotte", description: "R&B star Miguel brings his CAOS Tour to The Fillmore Charlotte for an unforgettable night of music.", startDate: "2026-03-31 20:00:00", endDate: "2026-03-31 23:00:00", venueName: "The Fillmore Charlotte", venueAddress: "820 Hamilton St, Charlotte, NC 28206", neighborhood: "NoDa", category: "concerts", isFeatured: "yes", status: "published" },
  { title: "Charlotte Food Truck Friday", slug: "food-truck-friday-apr-3", description: "Over 20 food trucks gather at South End for the weekly Food Truck Friday. Live DJ, craft beer garden, and family-friendly fun.", startDate: "2026-04-03 17:00:00", endDate: "2026-04-03 21:00:00", venueName: "Sycamore Brewing", venueAddress: "2161 Hawkins St, Charlotte, NC 28203", neighborhood: "South End", category: "food-drink", isFeatured: "no", status: "published" },
  { title: "Comedy Night at The Comedy Zone", slug: "comedy-zone-apr-4", description: "Saturday night comedy showcase featuring nationally touring comedians and local Charlotte talent.", startDate: "2026-04-04 20:00:00", endDate: "2026-04-04 22:30:00", venueName: "The Comedy Zone", venueAddress: "900 NC Music Factory Blvd, Charlotte, NC 28206", neighborhood: "NoDa", category: "nightlife", isFeatured: "no", status: "published" },
  { title: "Matthews Community Egg Hunt", slug: "matthews-egg-hunt-apr-4", description: "Annual community egg hunt for kids ages 2-12. Free photos with the Easter Bunny, face painting, and spring crafts.", startDate: "2026-04-04 10:00:00", endDate: "2026-04-04 13:00:00", venueName: "Stumptown Park", venueAddress: "120 N Trade St, Matthews, NC 28105", neighborhood: "Matthews", category: "family", isFeatured: "no", status: "published" },

  // APRIL 2026
  { title: "Charlotte SHOUT!", slug: "charlotte-shout-2026", description: "Charlotte's signature spring arts festival returns with 17 days of performances, installations, and cultural events across Uptown. Free and ticketed events.", startDate: "2026-04-10 12:00:00", endDate: "2026-04-26 22:00:00", venueName: "Various Uptown Venues", venueAddress: "Uptown Charlotte, NC", neighborhood: "Uptown", category: "festivals", isFeatured: "yes", status: "published" },
  { title: "Taste of Charlotte 2026", slug: "taste-of-charlotte-2026", description: "Charlotte's premier food festival featuring 100+ restaurants, celebrity chef demos, live music, and family activities in Uptown.", startDate: "2026-04-17 11:00:00", endDate: "2026-04-19 21:00:00", venueName: "Tryon Street", venueAddress: "N Tryon St, Charlotte, NC 28202", neighborhood: "Uptown", category: "food-drink", isFeatured: "yes", status: "published" },
  { title: "Carolina Open Air 2026", slug: "carolina-open-air-2026", description: "Two-day outdoor rock and metal festival featuring major headliners and emerging artists at PNC Music Pavilion.", startDate: "2026-04-24 14:00:00", endDate: "2026-04-25 23:00:00", venueName: "PNC Music Pavilion", venueAddress: "5800 Pavilion Blvd, Charlotte, NC 28262", neighborhood: "University City", category: "concerts", isFeatured: "yes", status: "published" },
  { title: "Tuck Fest 2026", slug: "tuck-fest-2026", description: "Outdoor adventure festival at the U.S. National Whitewater Center featuring live music, trail running, kayaking, climbing, and more.", startDate: "2026-04-24 10:00:00", endDate: "2026-04-25 20:00:00", venueName: "U.S. National Whitewater Center", venueAddress: "5000 Whitewater Center Pkwy, Charlotte, NC 28214", neighborhood: "Steele Creek", category: "festivals", isFeatured: "yes", status: "published" },
  { title: "Charlotte Earth Day Festival", slug: "charlotte-earth-day-2026", description: "Celebrate Earth Day with eco-friendly vendors, sustainability workshops, tree plantings, and live music at Freedom Park.", startDate: "2026-04-22 10:00:00", endDate: "2026-04-22 16:00:00", venueName: "Freedom Park", venueAddress: "1900 East Blvd, Charlotte, NC 28203", neighborhood: "Dilworth", category: "free", isFeatured: "no", status: "published" },
  { title: "Regional Festival of India", slug: "festival-of-india-2026", description: "Annual celebration of Indian culture with traditional dance, music, authentic cuisine, and cultural exhibitions.", startDate: "2026-04-18 11:00:00", endDate: "2026-04-18 20:00:00", venueName: "Charlotte Convention Center", venueAddress: "501 S College St, Charlotte, NC 28202", neighborhood: "Uptown", category: "festivals", isFeatured: "no", status: "published" },
  { title: "Dilworth Home Tour", slug: "dilworth-home-tour-2026", description: "Tour historic homes in one of Charlotte's most charming neighborhoods. Proceeds benefit Dilworth Community Development Association.", startDate: "2026-04-25 10:00:00", endDate: "2026-04-25 17:00:00", venueName: "Dilworth Neighborhood", venueAddress: "East Blvd, Charlotte, NC 28203", neighborhood: "Dilworth", category: "community", isFeatured: "no", status: "published" },
  { title: "Queen City Blues Festival", slug: "queen-city-blues-fest-2026", description: "The 8th Annual Queen City Blues Festival featuring legendary blues artists and the Blues Is Alright Tour.", startDate: "2026-04-11 19:00:00", endDate: "2026-04-11 23:00:00", venueName: "Bojangles Coliseum", venueAddress: "2700 E Independence Blvd, Charlotte, NC 28205", neighborhood: "Elizabeth", category: "concerts", isFeatured: "no", status: "published" },
  { title: "Charlotte StrEATs Festival", slug: "charlotte-streets-festival-2026", description: "Street food festival celebrating Charlotte's diverse culinary scene with 50+ food vendors, craft cocktails, and live entertainment.", startDate: "2026-04-12 12:00:00", endDate: "2026-04-12 20:00:00", venueName: "Camp North End", venueAddress: "1824 Statesville Ave, Charlotte, NC 28206", neighborhood: "NoDa", category: "food-drink", isFeatured: "no", status: "published" },
  { title: "Chalk the Walk", slug: "chalk-the-walk-2026", description: "Community chalk art festival where artists of all ages create colorful masterpieces on the sidewalks of NoDa.", startDate: "2026-04-19 10:00:00", endDate: "2026-04-19 16:00:00", venueName: "NoDa Arts District", venueAddress: "North Davidson St, Charlotte, NC 28206", neighborhood: "NoDa", category: "arts-culture", isFeatured: "no", status: "published" },
  { title: "Kids' Science Saturday at Discovery Place", slug: "science-saturday-apr-2026", description: "Hands-on science experiments, planetarium shows, and STEM activities for kids ages 5-12. Free with museum admission.", startDate: "2026-04-05 10:00:00", endDate: "2026-04-05 15:00:00", venueName: "Discovery Place Science", venueAddress: "301 N Tryon St, Charlotte, NC 28202", neighborhood: "Uptown", category: "family", isFeatured: "no", status: "published" },
  { title: "Montford Drive Art Walk", slug: "montford-art-walk-apr-2026", description: "Monthly art walk along Montford Drive featuring local artists, pop-up galleries, and live music at participating restaurants.", startDate: "2026-04-10 18:00:00", endDate: "2026-04-10 21:00:00", venueName: "Montford Drive", venueAddress: "Montford Dr, Charlotte, NC 28209", neighborhood: "Montford", category: "arts-culture", isFeatured: "no", status: "published" },
  { title: "Ballantyne Beer Fest", slug: "ballantyne-beer-fest-2026", description: "Annual craft beer festival featuring 40+ local and regional breweries, food trucks, and live music in Ballantyne.", startDate: "2026-04-18 13:00:00", endDate: "2026-04-18 18:00:00", venueName: "Ballantyne Village", venueAddress: "11325 N Community House Rd, Charlotte, NC 28277", neighborhood: "Ballantyne", category: "food-drink", isFeatured: "no", status: "published" },

  // MAY 2026
  { title: "Speed Street Festival", slug: "speed-street-2026", description: "Charlotte's legendary motorsports festival returns with live music, NASCAR driver appearances, racing simulators, and family activities.", startDate: "2026-05-22 11:00:00", endDate: "2026-05-24 21:00:00", venueName: "Uptown Charlotte", venueAddress: "N Tryon St, Charlotte, NC 28202", neighborhood: "Uptown", category: "festivals", isFeatured: "yes", status: "published" },
  { title: "Coca-Cola 600", slug: "coca-cola-600-2026", description: "NASCAR's longest race of the season at Charlotte Motor Speedway. A Memorial Day weekend tradition since 1960.", startDate: "2026-05-24 18:00:00", endDate: "2026-05-24 23:00:00", venueName: "Charlotte Motor Speedway", venueAddress: "5555 Concord Pkwy S, Concord, NC 28027", neighborhood: "Huntersville", category: "sports", isFeatured: "yes", status: "published" },
  { title: "Charlotte Pride Festival", slug: "charlotte-pride-2026", description: "Annual celebration of Charlotte's LGBTQ+ community with a parade, live performances, vendors, and community organizations.", startDate: "2026-05-16 12:00:00", endDate: "2026-05-17 18:00:00", venueName: "First Ward Park", venueAddress: "301 E 7th St, Charlotte, NC 28202", neighborhood: "Uptown", category: "community", isFeatured: "yes", status: "published" },
  { title: "Yiasou Greek Festival", slug: "yiasou-greek-festival-2026", description: "Charlotte's beloved Greek festival with authentic food, traditional dance, live music, and cultural exhibits.", startDate: "2026-05-07 11:00:00", endDate: "2026-05-10 21:00:00", venueName: "Holy Trinity Greek Orthodox Cathedral", venueAddress: "600 East Blvd, Charlotte, NC 28203", neighborhood: "Dilworth", category: "food-drink", isFeatured: "yes", status: "published" },
  { title: "Davidson Farmer's Market Opening Day", slug: "davidson-farmers-market-may-2026", description: "Opening day of the Davidson Farmer's Market season with fresh produce, baked goods, flowers, and local artisan products.", startDate: "2026-05-02 08:00:00", endDate: "2026-05-02 12:00:00", venueName: "Downtown Davidson", venueAddress: "Main St, Davidson, NC 28036", neighborhood: "Davidson", category: "markets", isFeatured: "no", status: "published" },
  { title: "Elizabeth Neighborhood 5K", slug: "elizabeth-5k-may-2026", description: "Annual 5K run/walk through the historic Elizabeth neighborhood. Post-race party with food, drinks, and live music.", startDate: "2026-05-09 08:00:00", endDate: "2026-05-09 11:00:00", venueName: "Independence Park", venueAddress: "300 Hawthorne Ln, Charlotte, NC 28204", neighborhood: "Elizabeth", category: "community", isFeatured: "no", status: "published" },
  { title: "Myers Park Garden Tour", slug: "myers-park-garden-tour-2026", description: "Tour stunning private gardens in one of Charlotte's most prestigious neighborhoods. Proceeds benefit local garden clubs.", startDate: "2026-05-16 10:00:00", endDate: "2026-05-16 16:00:00", venueName: "Myers Park", venueAddress: "Queens Rd, Charlotte, NC 28207", neighborhood: "Myers Park", category: "community", isFeatured: "no", status: "published" },
  { title: "South End Brewery Crawl", slug: "south-end-brewery-crawl-may-2026", description: "Self-guided brewery crawl through South End's 10+ craft breweries. Passport stamps earn prizes at each stop.", startDate: "2026-05-23 13:00:00", endDate: "2026-05-23 20:00:00", venueName: "South End Breweries", venueAddress: "South End, Charlotte, NC 28203", neighborhood: "South End", category: "food-drink", isFeatured: "no", status: "published" },
  { title: "Family Movie Night at Freedom Park", slug: "family-movie-night-may-2026", description: "Free outdoor movie screening under the stars at Freedom Park. Bring blankets and lawn chairs. Concessions available.", startDate: "2026-05-15 19:30:00", endDate: "2026-05-15 22:00:00", venueName: "Freedom Park", venueAddress: "1900 East Blvd, Charlotte, NC 28203", neighborhood: "Dilworth", category: "family", isFeatured: "no", status: "published" },
  { title: "NoDa Night Market", slug: "noda-night-market-may-2026", description: "Monthly night market in NoDa featuring local artisans, vintage finds, street food, and live music.", startDate: "2026-05-08 18:00:00", endDate: "2026-05-08 22:00:00", venueName: "NoDa Arts District", venueAddress: "North Davidson St, Charlotte, NC 28206", neighborhood: "NoDa", category: "markets", isFeatured: "no", status: "published" },
  { title: "Jazz at the Bechtler", slug: "jazz-bechtler-may-2026", description: "Monthly jazz concert series at the Bechtler Museum of Modern Art. Enjoy world-class jazz in an intimate museum setting.", startDate: "2026-05-01 18:00:00", endDate: "2026-05-01 21:00:00", venueName: "Bechtler Museum of Modern Art", venueAddress: "420 S Tryon St, Charlotte, NC 28202", neighborhood: "Uptown", category: "concerts", isFeatured: "no", status: "published" },
  { title: "Steele Creek Outdoor Movie", slug: "steele-creek-movie-may-2026", description: "Free outdoor movie screening at Berewick Park. Family-friendly film with food trucks and pre-show activities.", startDate: "2026-05-22 19:00:00", endDate: "2026-05-22 22:00:00", venueName: "Berewick Park", venueAddress: "9801 S Tryon St, Charlotte, NC 28273", neighborhood: "Steele Creek", category: "free", isFeatured: "no", status: "published" },

  // JUNE 2026
  { title: "Juneteenth CLT Festival", slug: "juneteenth-clt-2026", description: "Annual Juneteenth celebration with live music, cultural performances, art exhibits, food vendors, and community resources.", startDate: "2026-06-19 11:00:00", endDate: "2026-06-19 20:00:00", venueName: "First Ward Park", venueAddress: "301 E 7th St, Charlotte, NC 28202", neighborhood: "Uptown", category: "festivals", isFeatured: "yes", status: "published" },
  { title: "Charlotte FC vs Inter Miami", slug: "charlotte-fc-inter-miami-jun-2026", description: "MLS matchup between Charlotte FC and Inter Miami at Bank of America Stadium. Don't miss the Crown's electric atmosphere!", startDate: "2026-06-06 19:30:00", endDate: "2026-06-06 22:00:00", venueName: "Bank of America Stadium", venueAddress: "800 S Mint St, Charlotte, NC 28202", neighborhood: "Uptown", category: "sports", isFeatured: "yes", status: "published" },
  { title: "Latin American Festival", slug: "latin-american-festival-2026", description: "Charlotte's largest celebration of Latin American culture with traditional music, dance, food, and art from 20+ countries.", startDate: "2026-06-13 12:00:00", endDate: "2026-06-14 20:00:00", venueName: "Symphony Park", venueAddress: "4400 Sharon Rd, Charlotte, NC 28211", neighborhood: "Myers Park", category: "festivals", isFeatured: "no", status: "published" },
  { title: "Cornelius Art Walk", slug: "cornelius-art-walk-jun-2026", description: "Monthly art walk through downtown Cornelius featuring local artists, live demonstrations, and pop-up galleries.", startDate: "2026-06-05 18:00:00", endDate: "2026-06-05 21:00:00", venueName: "Downtown Cornelius", venueAddress: "Main St, Cornelius, NC 28031", neighborhood: "Cornelius", category: "arts-culture", isFeatured: "no", status: "published" },
  { title: "University City Food Fest", slug: "uncc-food-fest-jun-2026", description: "Food festival near UNC Charlotte campus featuring international cuisine, food trucks, and cooking demonstrations.", startDate: "2026-06-20 11:00:00", endDate: "2026-06-20 19:00:00", venueName: "University City", venueAddress: "University City Blvd, Charlotte, NC 28262", neighborhood: "University City", category: "food-drink", isFeatured: "no", status: "published" },
  { title: "Huntersville Summer Kick-Off", slug: "huntersville-summer-kickoff-2026", description: "Annual summer kick-off celebration with live music, food trucks, kids' activities, and a spectacular fireworks show.", startDate: "2026-06-06 16:00:00", endDate: "2026-06-06 22:00:00", venueName: "Veterans Park", venueAddress: "105 Gilead Rd, Huntersville, NC 28078", neighborhood: "Huntersville", category: "family", isFeatured: "no", status: "published" },
  { title: "Eastway Community Block Party", slug: "eastway-block-party-jun-2026", description: "Neighborhood block party with live music, food, games, and community resources. Free admission for all.", startDate: "2026-06-14 12:00:00", endDate: "2026-06-14 18:00:00", venueName: "Eastway Regional Rec Center", venueAddress: "3150 Eastway Dr, Charlotte, NC 28205", neighborhood: "Eastway", category: "free", isFeatured: "no", status: "published" },
  { title: "Mint Hill Madness", slug: "mint-hill-madness-jun-2026", description: "Annual community festival with carnival rides, live entertainment, food vendors, and a classic car show.", startDate: "2026-06-20 10:00:00", endDate: "2026-06-21 20:00:00", venueName: "Mint Hill Veterans Memorial Park", venueAddress: "4430 Mint Hill Village Ln, Mint Hill, NC 28227", neighborhood: "Mint Hill", category: "festivals", isFeatured: "no", status: "published" },
  { title: "Pineville Summer Concert Series", slug: "pineville-concert-jun-2026", description: "Free outdoor concert in downtown Pineville featuring local bands, food trucks, and family activities.", startDate: "2026-06-12 18:00:00", endDate: "2026-06-12 21:00:00", venueName: "Pineville Lake Park", venueAddress: "1000 Johnston Dr, Pineville, NC 28134", neighborhood: "Pineville", category: "concerts", isFeatured: "no", status: "published" },
  { title: "Indian Trail Heritage Festival", slug: "indian-trail-heritage-2026", description: "Celebrate Indian Trail's heritage with historical exhibits, live music, local food, and family-friendly activities.", startDate: "2026-06-27 10:00:00", endDate: "2026-06-27 18:00:00", venueName: "Crossing Paths Park", venueAddress: "6200 Old Monroe Rd, Indian Trail, NC 28079", neighborhood: "Indian Trail", category: "community", isFeatured: "no", status: "published" },
  { title: "Mooresville Independence Day Celebration", slug: "mooresville-july4-preview-2026", description: "Early Independence Day celebration with patriotic music, food vendors, kids' zone, and fireworks over Lake Norman.", startDate: "2026-06-28 16:00:00", endDate: "2026-06-28 22:00:00", venueName: "Downtown Mooresville", venueAddress: "Main St, Mooresville, NC 28115", neighborhood: "Mooresville", category: "family", isFeatured: "no", status: "published" },
  { title: "Camp North End Summer Night Market", slug: "camp-north-end-night-market-jun-2026", description: "Evening market at Camp North End with local vendors, artisan goods, street food, craft cocktails, and live DJ.", startDate: "2026-06-13 17:00:00", endDate: "2026-06-13 22:00:00", venueName: "Camp North End", venueAddress: "1824 Statesville Ave, Charlotte, NC 28206", neighborhood: "NoDa", category: "markets", isFeatured: "no", status: "published" },
  { title: "Charlotte Hornets Draft Watch Party", slug: "hornets-draft-party-2026", description: "Watch the NBA Draft with fellow Hornets fans at the Spectrum Center. Free admission with food and drink specials.", startDate: "2026-06-25 19:00:00", endDate: "2026-06-25 23:00:00", venueName: "Spectrum Center", venueAddress: "333 E Trade St, Charlotte, NC 28202", neighborhood: "Uptown", category: "sports", isFeatured: "no", status: "published" },

  // RECURRING WEEKLY EVENTS
  { title: "Uptown Farmers Market (Weekly)", slug: "uptown-farmers-market-weekly", description: "Every Saturday morning, shop local produce, artisan goods, and handmade crafts from Charlotte-area farms and makers.", startDate: "2026-04-04 09:00:00", endDate: "2026-04-04 13:00:00", venueName: "7th Street Public Market", venueAddress: "224 E 7th St, Charlotte, NC 28202", neighborhood: "Uptown", category: "markets", isFeatured: "no", isRecurring: "yes", status: "published" },
  { title: "Trivia Night at Wooden Robot Brewery", slug: "trivia-wooden-robot-weekly", description: "Weekly trivia night at one of South End's favorite breweries. Teams of up to 6, prizes for top 3 finishers.", startDate: "2026-04-01 19:00:00", endDate: "2026-04-01 21:00:00", venueName: "Wooden Robot Brewery", venueAddress: "1440 S Tryon St, Charlotte, NC 28203", neighborhood: "South End", category: "nightlife", isFeatured: "no", isRecurring: "yes", status: "published" },
  { title: "Free Yoga at Romare Bearden Park", slug: "free-yoga-weekly", description: "Every Saturday morning, join a free outdoor yoga session overlooking the Charlotte skyline. All levels welcome.", startDate: "2026-04-04 09:00:00", endDate: "2026-04-04 10:00:00", venueName: "Romare Bearden Park", venueAddress: "300 S Church St, Charlotte, NC 28202", neighborhood: "Uptown", category: "free", isFeatured: "no", isRecurring: "yes", status: "published" },
  { title: "Open Mic Night at Evening Muse", slug: "open-mic-evening-muse-weekly", description: "Weekly open mic night at NoDa's iconic music venue. Sign up at 7pm, performances start at 8pm. All genres welcome.", startDate: "2026-04-02 19:00:00", endDate: "2026-04-02 22:00:00", venueName: "Evening Muse", venueAddress: "3227 N Davidson St, Charlotte, NC 28205", neighborhood: "NoDa", category: "concerts", isFeatured: "no", isRecurring: "yes", status: "published" },
];

async function main() {
  const conn = await mysql.createConnection(DATABASE_URL);
  let inserted = 0;
  let skipped = 0;

  for (const ev of events) {
    try {
      await conn.execute(
        `INSERT INTO events (title, slug, description, startDate, endDate, venueName, venueAddress, neighborhood, category, isFeatured, isRecurring, status, createdAt, updatedAt)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
         ON DUPLICATE KEY UPDATE title=VALUES(title)`,
        [
          ev.title,
          ev.slug,
          ev.description ?? null,
          ev.startDate,
          ev.endDate ?? null,
          ev.venueName ?? null,
          ev.venueAddress ?? null,
          ev.neighborhood ?? null,
          ev.category,
          ev.isFeatured ?? "no",
          ev.isRecurring ?? "no",
          ev.status ?? "published",
        ]
      );
      inserted++;
      console.log(`✓ ${ev.title}`);
    } catch (err) {
      console.error(`✗ ${ev.title}: ${err.message}`);
      skipped++;
    }
  }

  console.log(`\nDone: ${inserted} inserted, ${skipped} skipped`);
  await conn.end();
}

main().catch(console.error);
